# Generated by Django 5.2 on 2025-07-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(max_length=500, verbose_name='Title')),
                ('simage1', models.ImageField(upload_to='images/', verbose_name='Student 1 Image')),
                ('simage2', models.ImageField(upload_to='images/', verbose_name='Student 2 Image')),
                ('cerimage', models.ImageField(upload_to='images/', verbose_name='Certificate Image')),
                ('fbrimage', models.ImageField(upload_to='images/', verbose_name='FBR Image')),
                ('fbrtitle', models.CharField(default='FBR Certificate', max_length=50, verbose_name='FBR Title')),
                ('fbrlink', models.URLField(default='https://fbr.gov.pk/', max_length=100, verbose_name='FBR Link')),
                ('secpimage', models.ImageField(upload_to='images/', verbose_name='SECP Image')),
                ('secptitle', models.CharField(default='SCEP Certificate', max_length=50, verbose_name='SECP Title')),
                ('secplink', models.CharField(default='https://www.secp.gov.pk/', max_length=100, verbose_name='SECP Link')),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(max_length=500, verbose_name='Title')),
                ('image1', models.ImageField(upload_to='images/', verbose_name='Image 1')),
                ('image2', models.ImageField(upload_to='images/', verbose_name='Image 2')),
                ('image3', models.ImageField(upload_to='images/', verbose_name='Image 3')),
                ('image4', models.ImageField(upload_to='images/', verbose_name='Image 4')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='10K', max_length=10, verbose_name='Value')),
                ('text', models.TextField(default='Active Students On Website', max_length=200, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('course', models.TextField(max_length=100, verbose_name='Course')),
                ('teacher_image', models.ImageField(upload_to='images/', verbose_name='Teacher Image')),
                ('phone', models.CharField(db_comment='Please start with country code', verbose_name='Phone Number')),
                ('lesson', models.IntegerField(default=0, verbose_name='Total Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Webinars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Webinar Name')),
                ('text', models.CharField(max_length=300, verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Course Name')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('students', models.IntegerField(default=1, verbose_name='Total Students')),
                ('desc', models.TextField(default='Right your text here.', max_length=2000, verbose_name='Description')),
                ('status', models.BinaryField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], verbose_name='Status')),
                ('price', models.CharField(max_length=20, verbose_name='Price')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Talento_app.teachers', verbose_name='Teacher')),
            ],
        ),
    ]
