# Generated by Django 5.2 on 2025-07-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talento_app', '0002_alter_courses_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.FloatField(max_length=20, verbose_name='Price'),
        ),
    ]
