# Generated by Django 5.2 on 2025-07-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talento_app', '0003_alter_courses_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email_address', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('phone', models.CharField(db_comment='Please start with country code', verbose_name='Phone Number')),
                ('comments', models.TextField(max_length=5000, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('text_information', models.CharField(max_length=50, verbose_name='Information text')),
                ('image_1', models.ImageField(upload_to='images/', verbose_name='Image 1')),
                ('image_3', models.ImageField(upload_to='images/', verbose_name='Image 3')),
                ('image_2', models.TextField(max_length=1000, verbose_name='Testimonial')),
                ('phone_num', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('link_1', models.CharField(max_length=20, verbose_name='Link_1')),
                ('link_2', models.CharField(max_length=20, verbose_name='Link_2')),
                ('link_3', models.CharField(max_length=20, verbose_name='Link_3')),
                ('link_4', models.CharField(max_length=20, verbose_name='Link_4')),
                ('link_5', models.CharField(max_length=20, verbose_name='Link_5 ')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200, verbose_name='Question')),
                ('answer', models.TextField(max_length=5000, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('course', models.CharField(max_length=100, verbose_name='Course')),
                ('testimon', models.TextField(max_length=1000, verbose_name='Testimonial')),
            ],
        ),
    ]
