# Generated by Django 5.2 on 2025-07-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talento_app', '0004_contactus_footermodel_frequentlyaskedquestions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermodel',
            name='image_2',
            field=models.ImageField(upload_to='images/', verbose_name='Image 2'),
        ),
    ]
