# Generated by Django 5.2 on 2025-07-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talento_app', '0005_alter_footermodel_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='footermodel',
            name='link_1_of_image_1',
            field=models.CharField(default='No link', max_length=500, verbose_name='Link of Image 1'),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='link_2_of_image_2',
            field=models.CharField(default='No link', max_length=500, verbose_name='Link of Image 2'),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='link_3_of_image_3',
            field=models.CharField(default='No link', max_length=500, verbose_name='Link of Image 3'),
        ),
    ]
