# Generated by Django 5.2 on 2025-07-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talento_app', '0006_footermodel_link_1_of_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footermodel',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='footermodel',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='footermodel',
            name='link_3',
        ),
        migrations.RemoveField(
            model_name='footermodel',
            name='link_4',
        ),
        migrations.RemoveField(
            model_name='footermodel',
            name='link_5',
        ),
        migrations.AddField(
            model_name='footermodel',
            name='quick_image_1',
            field=models.ImageField(default='images/satisfied-pic3.jpg', max_length=20, upload_to='images/', verbose_name='Quick Image 1'),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='quick_image_2',
            field=models.ImageField(default='images/satisfied-pic3.jpg', max_length=20, upload_to='images/', verbose_name='Quick Image 2'),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='quick_image_3',
            field=models.ImageField(default='images/satisfied-pic3.jpg', max_length=20, upload_to='images/', verbose_name='Quick Image 3'),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='quick_image_4',
            field=models.ImageField(default='images/satisfied-pic3.jpg', max_length=20, upload_to='images/', verbose_name='Quick Image 4'),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='quick_image_5',
            field=models.ImageField(default='images/satisfied-pic3.jpg', max_length=20, upload_to='images/', verbose_name='Quick Image 5'),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='quick_link_1',
            field=models.CharField(default='No link', max_length=20, verbose_name='Quick Link 1'),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='quick_link_2',
            field=models.CharField(default='No link', max_length=20, verbose_name='Quick Link 2'),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='quick_link_3',
            field=models.CharField(default='No link', max_length=20, verbose_name='Quick Link 3'),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='quick_link_4',
            field=models.CharField(default='No link', max_length=20, verbose_name='Quick Link 4'),
        ),
        migrations.AddField(
            model_name='footermodel',
            name='quick_link_5',
            field=models.CharField(default='No link', max_length=20, verbose_name='Quick Link 5'),
        ),
    ]
