# Generated by Django 5.2 on 2025-07-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talento_app', '0007_remove_footermodel_link_1_remove_footermodel_link_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermodel',
            name='link_1_of_image_1',
            field=models.URLField(default='No link', max_length=500, verbose_name='Link of Image 1'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='link_2_of_image_2',
            field=models.URLField(default='No link', max_length=500, verbose_name='Link of Image 2'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='link_3_of_image_3',
            field=models.URLField(default='No link', max_length=500, verbose_name='Link of Image 3'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_1',
            field=models.URLField(default='No link', max_length=20, verbose_name='Quick Link 1'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_2',
            field=models.URLField(default='No link', max_length=20, verbose_name='Quick Link 2'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_3',
            field=models.URLField(default='No link', max_length=20, verbose_name='Quick Link 3'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_4',
            field=models.URLField(default='No link', max_length=20, verbose_name='Quick Link 4'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_5',
            field=models.URLField(default='No link', max_length=20, verbose_name='Quick Link 5'),
        ),
    ]
