# Generated by Django 5.2 on 2025-07-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talento_app', '0008_alter_footermodel_link_1_of_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermodel',
            name='quick_image_1',
            field=models.CharField(default='No link', max_length=20, verbose_name='Quick Image 1'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_image_2',
            field=models.CharField(default='No link', max_length=20, verbose_name='Quick Image 2'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_image_3',
            field=models.CharField(default='No link', max_length=20, verbose_name='Quick Image 3'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_image_4',
            field=models.CharField(default='No link', max_length=20, verbose_name='Quick Image 4'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_image_5',
            field=models.CharField(default='No link', max_length=20, verbose_name='Quick Image 5'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_1',
            field=models.URLField(choices=[('FAQs', '#'), ('Course', 'allcourses'), ('Events', 'allwebinars'), ('Contact Us', '#'), ('About Us', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link 1'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_2',
            field=models.URLField(choices=[('FAQs', '#'), ('Course', 'allcourses'), ('Events', 'allwebinars'), ('Contact Us', '#'), ('About Us', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link 2'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_3',
            field=models.URLField(choices=[('FAQs', '#'), ('Course', 'allcourses'), ('Events', 'allwebinars'), ('Contact Us', '#'), ('About Us', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link 3'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_4',
            field=models.URLField(choices=[('FAQs', '#'), ('Course', 'allcourses'), ('Events', 'allwebinars'), ('Contact Us', '#'), ('About Us', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link 4'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_5',
            field=models.URLField(choices=[('FAQs', '#'), ('Course', 'allcourses'), ('Events', 'allwebinars'), ('Contact Us', '#'), ('About Us', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link 5'),
        ),
    ]
