# Generated by Django 5.2 on 2025-07-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Talento_app', '0011_alter_footermodel_quick_link_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footermodel',
            old_name='quick_image_1',
            new_name='quick_link_text_1',
        ),
        migrations.RenameField(
            model_name='footermodel',
            old_name='quick_image_2',
            new_name='quick_link_text_2',
        ),
        migrations.RenameField(
            model_name='footermodel',
            old_name='quick_image_3',
            new_name='quick_link_text_3',
        ),
        migrations.RenameField(
            model_name='footermodel',
            old_name='quick_image_4',
            new_name='quick_link_text_4',
        ),
        migrations.RenameField(
            model_name='footermodel',
            old_name='quick_image_5',
            new_name='quick_link_text_5',
        ),
    ]
