# Generated by Django 5.2 on 2025-07-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talento_app', '0012_rename_quick_image_1_footermodel_quick_link_text_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
