# Generated by Django 5.2 on 2025-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talento_app', '0014_alter_contactus_phone_alter_testimonial_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_1',
            field=models.CharField(choices=[('#faq-section', '#faq-section'), ('allcourses', 'allcourses'), ('allwebinars', 'allwebinars'), ('#contactus', '#contactus'), ('aboutus', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link Url 1'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_2',
            field=models.CharField(choices=[('#faq-section', '#faq-section'), ('allcourses', 'allcourses'), ('allwebinars', 'allwebinars'), ('#contactus', '#contactus'), ('aboutus', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link Url 2'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_3',
            field=models.CharField(choices=[('#faq-section', '#faq-section'), ('allcourses', 'allcourses'), ('allwebinars', 'allwebinars'), ('#contactus', '#contactus'), ('aboutus', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link Url 3'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_4',
            field=models.CharField(choices=[('#faq-section', '#faq-section'), ('allcourses', 'allcourses'), ('allwebinars', 'allwebinars'), ('#contactus', '#contactus'), ('aboutus', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link Url 4'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_5',
            field=models.CharField(choices=[('#faq-section', '#faq-section'), ('allcourses', 'allcourses'), ('allwebinars', 'allwebinars'), ('#contactus', '#contactus'), ('aboutus', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link Url 5'),
        ),
    ]
