# Generated by Django 5.2 on 2025-07-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talento_app', '0016_alter_footermodel_quick_link_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_1',
            field=models.CharField(choices=[('allcourses', 'Courses'), ('allwebinars', 'allwebinars'), ('aboutus', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link Url 1'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_2',
            field=models.CharField(choices=[('allcourses', 'Courses'), ('allwebinars', 'allwebinars'), ('aboutus', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link Url 2'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_3',
            field=models.CharField(choices=[('#faq-section', 'FAQs'), ('#contactus', '#contactus')], default='No link', max_length=20, verbose_name='Quick Link Url 3'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_4',
            field=models.CharField(choices=[('#faq-section', 'FAQs'), ('#contactus', '#contactus')], default='No link', max_length=20, verbose_name='Quick Link Url 4'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_5',
            field=models.CharField(choices=[('allcourses', 'Courses'), ('allwebinars', 'allwebinars'), ('aboutus', 'aboutus')], default='No link', max_length=20, verbose_name='Quick Link Url 5'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_text_1',
            field=models.CharField(choices=[('Course', 'Course'), ('Events', 'Events'), ('About', 'About')], default='No link', max_length=20, verbose_name='Quick Link 1'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_text_2',
            field=models.CharField(choices=[('Course', 'Course'), ('Events', 'Events'), ('About', 'About')], default='No link', max_length=20, verbose_name='Quick Link 2'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_text_3',
            field=models.CharField(choices=[('FAQs', 'FAQs'), ('Contact Us', 'Contact Us')], default='No link', max_length=20, verbose_name='Quick Link 3'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_text_4',
            field=models.CharField(choices=[('FAQs', 'FAQs'), ('Contact Us', 'Contact Us')], default='No link', max_length=20, verbose_name='Quick Link 4'),
        ),
        migrations.AlterField(
            model_name='footermodel',
            name='quick_link_text_5',
            field=models.CharField(choices=[('Course', 'Course'), ('Events', 'Events'), ('About', 'About')], default='No link', max_length=20, verbose_name='Quick Link 5'),
        ),
    ]
