# Generated by Django 5.2 on 2025-08-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='About Us Image')),
                ('contact_us_heading', models.CharField(max_length=100, verbose_name='Contact Us Heading')),
                ('contact_us_desc', models.TextField(max_length=1000, verbose_name='Contact Us Description')),
            ],
        ),
        migrations.CreateModel(
            name='AllHeadingAndDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(max_length=100, verbose_name='Hero Section Heading')),
                ('hero_desc', models.TextField(max_length=500, verbose_name='Hero Section Description')),
                ('transvocal_heading', models.CharField(max_length=100, verbose_name='Transvocal Heading')),
                ('transvocal_desc', models.TextField(max_length=500, verbose_name='Transvocal Description')),
                ('status_heading', models.CharField(max_length=100, verbose_name='Status Heading')),
                ('status_desc', models.TextField(max_length=500, verbose_name='Status Description')),
                ('marketplace_heading', models.CharField(max_length=100, verbose_name='Marketplace Heading')),
                ('marketplace_sub_heading', models.CharField(max_length=100, verbose_name='Marketplace Sub-Heading')),
                ('marketplace_desc', models.TextField(max_length=500, verbose_name='Marketplace Description')),
                ('insights_heading', models.CharField(max_length=100, verbose_name='Insights Heading')),
                ('insights_desc', models.TextField(max_length=300, verbose_name='Insights Description')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to='images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Question')),
                ('answer', models.TextField(max_length=500, verbose_name='Answer')),
                ('facebook_logo', models.ImageField(upload_to='images/', verbose_name='Facebook Logo')),
                ('facebook_link', models.URLField(max_length=1000, verbose_name='Facebook URL')),
                ('twitter_logo', models.ImageField(upload_to='images/', verbose_name='Twitter Logo')),
                ('twitter_link', models.URLField(max_length=1000, verbose_name='Twitter URL')),
                ('linkedIn_logo', models.ImageField(upload_to='images/', verbose_name='LinkedIn Logo')),
                ('linkedIn_link', models.URLField(max_length=1000, verbose_name='LinkedIn URL')),
                ('youtube_logo', models.ImageField(upload_to='images/', verbose_name='Youtube Logo')),
                ('youtube_link', models.URLField(max_length=1000, verbose_name='Youtube URL')),
                ('t', models.CharField(choices=[('Transvocal', 'Transvocal'), ('Interview AI', 'Interview AI'), ('Insight', 'Insight'), ('Marketplace', 'Marketplace')], verbose_name='Transvocal Name')),
                ('t_link', models.CharField(choices=[('Transvocal', '#transvocal'), ('Interview AI', '#'), ('Insight', '#insight'), ('Marketplace', '#marketplace')], verbose_name='Transvocal Link')),
                ('iai', models.CharField(choices=[('Transvocal', 'Transvocal'), ('Interview AI', 'Interview AI'), ('Insight', 'Insight'), ('Marketplace', 'Marketplace')], verbose_name='Interview AI Name')),
                ('iai_link', models.CharField(choices=[('Transvocal', '#transvocal'), ('Interview AI', '#'), ('Insight', '#insight'), ('Marketplace', '#marketplace')], verbose_name='Interview AI Link')),
                ('au', models.CharField(choices=[('About Us', 'About Us'), ('Contact Us', 'Contact Us'), ('Case Study', 'Case Study'), ('Blogs', 'Blogs'), ('Events', 'Events')], verbose_name='About Us Name')),
                ('au_link', models.CharField(choices=[('About Us', 'aboutus/'), ('Contact Us', 'contactus/'), ('Case Study', '#'), ('Blogs', '#'), ('Events', '#')], verbose_name='About Us Link')),
                ('cu', models.CharField(choices=[('About Us', 'About Us'), ('Contact Us', 'Contact Us'), ('Case Study', 'Case Study'), ('Blogs', 'Blogs'), ('Events', 'Events')], verbose_name='Contact Us Name')),
                ('cu_link', models.CharField(choices=[('About Us', 'aboutus/'), ('Contact Us', 'contactus/'), ('Case Study', '#'), ('Blogs', '#'), ('Events', '#')], verbose_name='Contact Us Link')),
                ('ins', models.CharField(choices=[('Transvocal', 'Transvocal'), ('Interview AI', 'Interview AI'), ('Insight', 'Insight'), ('Marketplace', 'Marketplace')], verbose_name='Insights Name')),
                ('ins_link', models.CharField(choices=[('Transvocal', '#transvocal'), ('Interview AI', '#'), ('Insight', '#insight'), ('Marketplace', '#marketplace')], verbose_name='Insights Link')),
                ('mk', models.CharField(choices=[('Transvocal', 'Transvocal'), ('Interview AI', 'Interview AI'), ('Insight', 'Insight'), ('Marketplace', 'Marketplace')], verbose_name='Marketplace Name')),
                ('mk_link', models.CharField(choices=[('Transvocal', '#transvocal'), ('Interview AI', '#'), ('Insight', '#insight'), ('Marketplace', '#marketplace')], verbose_name='Marketplace Link')),
                ('cs', models.CharField(choices=[('About Us', 'About Us'), ('Contact Us', 'Contact Us'), ('Case Study', 'Case Study'), ('Blogs', 'Blogs'), ('Events', 'Events')], verbose_name='Case Study Name')),
                ('cs_link', models.CharField(choices=[('About Us', 'aboutus/'), ('Contact Us', 'contactus/'), ('Case Study', '#'), ('Blogs', '#'), ('Events', '#')], verbose_name='Case Study Link')),
                ('b', models.CharField(choices=[('About Us', 'About Us'), ('Contact Us', 'Contact Us'), ('Case Study', 'Case Study'), ('Blogs', 'Blogs'), ('Events', 'Events')], verbose_name='Blogs Name')),
                ('b_link', models.CharField(choices=[('About Us', 'aboutus/'), ('Contact Us', 'contactus/'), ('Case Study', '#'), ('Blogs', '#'), ('Events', '#')], verbose_name='Transvocal Link')),
                ('ev', models.CharField(choices=[('About Us', 'About Us'), ('Contact Us', 'Contact Us'), ('Case Study', 'Case Study'), ('Blogs', 'Blogs'), ('Events', 'Events')], verbose_name='Events Name')),
                ('ev_link', models.CharField(choices=[('About Us', 'aboutus/'), ('Contact Us', 'contactus/'), ('Case Study', '#'), ('Blogs', '#'), ('Events', '#')], verbose_name='Events Link')),
            ],
        ),
        migrations.CreateModel(
            name='GetInTouchAndLetsWorkTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getintouch_desc', models.TextField(max_length=1000, verbose_name='Get In Touch Description')),
                ('email', models.CharField(default='Email: contact@apexai.com', max_length=70, verbose_name='Email')),
                ('phone', models.CharField(default='Phone/WhatsApp: +92-XXX-XXXXXXX', max_length=70, verbose_name='Phone')),
                ('lets_work_together_desc', models.TextField(max_length=1000, verbose_name='Lets Work Together Description')),
            ],
        ),
        migrations.CreateModel(
            name='MissionAndVisionandTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_desc', models.TextField(max_length=1000, verbose_name='Mission Description')),
                ('vision_desc', models.TextField(max_length=1000, verbose_name='Vision Description')),
                ('team_desc', models.TextField(max_length=1000, verbose_name='Team Description')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='200+', max_length=20, verbose_name='Dashboard')),
                ('desc', models.CharField(default='Users Onboard', max_length=50, verbose_name='Dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('name', models.CharField(default='Unknown', max_length=100, verbose_name='Name')),
                ('designation', models.CharField(default='Unknown', max_length=100, verbose_name='Designation')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100, verbose_name='Name')),
                ('person_designation', models.CharField(default='Unknown', max_length=100, verbose_name='Designation')),
                ('test', models.TextField(default='Nothing', max_length=1000, verbose_name='Testimonial')),
            ],
        ),
        migrations.CreateModel(
            name='TransvocalDashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to='images/', verbose_name='Dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatwedo_desc', models.TextField(max_length=500, verbose_name='What We Do Description')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseApexisAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WhyChooseApexAI_desc', models.TextField(max_length=500, verbose_name='Why Choose Apexis AI Description')),
            ],
        ),
        migrations.CreateModel(
            name='WhyReachOutToUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whyreachouttous_desc', models.TextField(max_length=300, verbose_name='Why Reach Out To Us Description')),
            ],
        ),
    ]
