# Generated by Django 5.2 on 2025-08-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apexisAI_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='About Us Image')),
                ('contact_us_heading', models.CharField(max_length=100, verbose_name='Contact Us Heading')),
                ('contact_us_desc', models.TextField(max_length=1000, verbose_name='Contact Us Description')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='Full Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('business', models.CharField(max_length=100, verbose_name='Business/Company Name')),
                ('project', models.CharField(max_length=100, verbose_name='Project in Mind')),
                ('details', models.TextField(max_length=2000, verbose_name='Details')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='contact_us_desc',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='contact_us_heading',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_us_desc',
            field=models.TextField(default='No Description', max_length=500, verbose_name='About Us Description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_us_heading',
            field=models.CharField(default='No Heading', max_length=100, verbose_name='About Us Heading'),
        ),
    ]
