# Generated by Django 5.2 on 2025-08-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apexisAI_app', '0002_contactus_contactusform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='images/b_image.webp', upload_to='images/', verbose_name='Dashboard'),
        ),
    ]
