# Generated by Django 5.2 on 2025-08-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apexisAI_app', '0003_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='images/profile logo.jpg', upload_to='images/', verbose_name='Dashboard'),
        ),
    ]
