# Generated by Django 5.2 on 2025-08-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apexisAI_app', '0005_alter_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='con_email',
            field=models.CharField(default='example@yourmail.com', max_length=50, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='footer',
            name='con_location',
            field=models.CharField(default='Karachi, Pakistan', max_length=50, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='footer',
            name='con_phone',
            field=models.CharField(default='+92 000 000 000', max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='au_link',
            field=models.CharField(choices=[('aboutus', 'About Us'), ('contactus', 'Contact Us'), ('#', 'Events')], verbose_name='About Us Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='b_link',
            field=models.CharField(choices=[('aboutus', 'About Us'), ('contactus', 'Contact Us'), ('#', 'Events')], verbose_name='Blog Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='cs_link',
            field=models.CharField(choices=[('aboutus', 'About Us'), ('contactus', 'Contact Us'), ('#', 'Events')], verbose_name='Case Study Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='cu_link',
            field=models.CharField(choices=[('aboutus', 'About Us'), ('contactus', 'Contact Us'), ('#', 'Events')], verbose_name='Contact Us Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='ev_link',
            field=models.CharField(choices=[('aboutus', 'About Us'), ('contactus', 'Contact Us'), ('#', 'Events')], verbose_name='Events Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='iai_link',
            field=models.CharField(choices=[('#transvocal', 'Transvocal'), ('#', 'Interview AI'), ('#insight', 'Insight'), ('#marketplace', 'Marketplace')], verbose_name='Interview AI Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='ins_link',
            field=models.CharField(choices=[('#transvocal', 'Transvocal'), ('#', 'Interview AI'), ('#insight', 'Insight'), ('#marketplace', 'Marketplace')], verbose_name='Insights Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='mk_link',
            field=models.CharField(choices=[('#transvocal', 'Transvocal'), ('#', 'Interview AI'), ('#insight', 'Insight'), ('#marketplace', 'Marketplace')], verbose_name='Marketplace Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='t_link',
            field=models.CharField(choices=[('#transvocal', 'Transvocal'), ('#', 'Interview AI'), ('#insight', 'Insight'), ('#marketplace', 'Marketplace')], verbose_name='Transvocal Link'),
        ),
    ]
