# Generated by Django 5.2 on 2025-08-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apexisAI_app', '0006_footer_con_email_footer_con_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='b_link',
            field=models.CharField(default='#', max_length=50, verbose_name='Blog Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='cs_link',
            field=models.CharField(default='#', max_length=50, verbose_name='Case Study Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='ev_link',
            field=models.CharField(default='#', max_length=50, verbose_name='Events Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='iai_link',
            field=models.CharField(choices=[('#transvocal', 'Transvocal'), ('#', 'Interview AI'), ('#insights', 'Insight'), ('#marketplace', 'Marketplace')], verbose_name='Interview AI Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='ins_link',
            field=models.CharField(choices=[('#transvocal', 'Transvocal'), ('#', 'Interview AI'), ('#insights', 'Insight'), ('#marketplace', 'Marketplace')], verbose_name='Insights Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='mk_link',
            field=models.CharField(choices=[('#transvocal', 'Transvocal'), ('#', 'Interview AI'), ('#insights', 'Insight'), ('#marketplace', 'Marketplace')], verbose_name='Marketplace Link'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='t_link',
            field=models.CharField(choices=[('#transvocal', 'Transvocal'), ('#', 'Interview AI'), ('#insights', 'Insight'), ('#marketplace', 'Marketplace')], verbose_name='Transvocal Link'),
        ),
    ]
